### ISSUE TITLE
Koodikatselmointi, 30.04 kl 09.00

### ISSUE THREAD

**Issue by Jonharju** [jhhr/bodylog#1]
-Selkeä kansiojako auttoi rakenteen tutkimisessa, mutta ehkä kannattaisi laitta toisiinsa liittyvät kansiot sisäkkäin. Tai en tiedä oliko vika vain minun koneessani, mutta sourcen sisällä oli 19 kansiota
-Graafisen käyttöliittymän rakenne ja ulkonäkö oli selkeä, ohjelman käyttö tuntui sujuvalta ja sen käytön omaksui hyvin sujuvasti
-Olet käsitellyt hyvin virhetilanteet, jotain mistä voisin itse otta paljon oppia
-Kuuluuko help/instructions avautua sovelluksen käynnistäessä? Jos näin, niin olisi ollut helpottavaa jos instructions ruudussa olisi ollut jotain pientä vinkkiä, vaikkakin käyttis on hyvin selkeä
-Minulla meni aika kauan yrittäessä laittaa uutta harjoitusta sovellukseen, se sanoi koko ajan että nimikenttä ei saa olla tyhjä, vaikka se ei ollutkaan tyhjä. En koskaan saanut selville mistä tämä johtui, joten en pystynyt kummemmin ohjelman toiminallisuutta testaamaan.

Onnea viime hetken korjauksiin!

**Comment by jhhr** [comment]
Kiitos palautteesta. En itsekään ole ihan tyytyväinen kansiojakoon, pelkäsin että koodi on ihan sekavaa kun luokkia on niin paljon mutta ehkä se on ihan siedettävä. Aluksi luokkia oli paljon pienessä määrässä pakkauksia ja se tuntui jotenkin sekavalta, joten jaottelin vain pari luokkaa kerrallaan moneen pakkaukseen ja koitin nimetä pakkaukset sen sisältämien luokkien toimintojen mukaan.

Help-ruudussa ei ollut vielä ohjeita sillä en ollut vielä kirjoittanut niitä. Tosiaan nimikentässä pitää painaa entteriä kirjoittamisen jälkeen ennen kuin nimi vaihtuu. Voisin lisätä tämän näiden komponenttien tooltippiin.
